apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
  namespace: demo
spec:
  replicas: 1
  selector: { matchLabels: { app: web, color: blue } }
  template:
    metadata: { labels: { app: web, color: blue } }
    spec:
      containers:
      - name: web
        image: DOCKERHUB_USER/bluegreen-demo:latest   
        ports: [{ containerPort: 80 }]
        envFrom:
          - configMapRef: { name: app-config }
          - secretRef:    { name: app-secret }
