name: CD GitOps (ArgoCD)

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  update-manifest:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get new image tag
        run: |
          echo "NEW_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Update k8s manifest with new image
        run: |
          sed -i "s|image: .*$|image: ${{ secrets.DOCKERHUB_USERNAME }}/bluegreen-demo:latest|" k8s/web-deploy-green.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/web-deploy-green.yaml
          git commit -m "CD: update image tag to $NEW_TAG"
          git push
